### ISSUE TITLE
Can it support router firmware?

### ISSUE THREAD

**Issue by zhefox** [FirmWire/FirmWire#9]
Can it support router firmware?I just want to simulate router operation.Look forward to your reply.

**Comment by grant-h** [comment]
Hello! FirmWire is specifically tailored for baseband firmware vendors (MTK and Samsung). This means much of the code related to them wouldn't be relevant. But the underlying framework outside of vendor directories (loader, emulator, peripheral creation) could be ported to other targets. This is because FirmWire is based upon generic dynamic analysis / emulation frameworks, avatar2 and PANDA. QEMU is the underlying emulator, so if avatar2, PANDA and that support your target architecture (ISA), then you should be able to reuse some code from FirmWire.
